scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['potential-barnacle-59vj45wj64h4q7q-9091.app.github.dev']
    scheme: https
